2019-04-01 08:00:13.490  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Operation timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:00:15.406  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:00:15.407 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:00:15.408  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:00:17.486  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:01:16.626  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 61106ms for sessionid 0x100fc439b1b0315
2019-04-01 08:01:16.630  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 61106ms for sessionid 0x100fc439b1b0315, closing socket connection and attempting reconnect
2019-04-01 08:01:18.438  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:02:11.352  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 54582ms for sessionid 0x100fc439b1b0315
2019-04-01 08:02:11.385  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 54582ms for sessionid 0x100fc439b1b0315, closing socket connection and attempting reconnect
2019-04-01 08:02:13.395  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:02:13.400 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:02:13.406  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:02:14.798  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:02:55.173  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 41651ms for sessionid 0x100fc439b1b0315
2019-04-01 08:02:55.195  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 41651ms for sessionid 0x100fc439b1b0315, closing socket connection and attempting reconnect
2019-04-01 08:02:56.987  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:03:53.260  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 57952ms for sessionid 0x100fc439b1b0315
2019-04-01 08:03:53.267  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 57952ms for sessionid 0x100fc439b1b0315, closing socket connection and attempting reconnect
2019-04-01 08:03:54.881  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:05:18.407  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 85027ms for sessionid 0x100fc439b1b0315
2019-04-01 08:05:18.417  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 85027ms for sessionid 0x100fc439b1b0315, closing socket connection and attempting reconnect
2019-04-01 08:05:19.571  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:05:19.579 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:05:19.582  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:05:21.016  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:05:21.016 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:05:21.018  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:05:22.370  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:05:22.371 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:05:22.371  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:39.384  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:39.396 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:39.414  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:40.558  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:40.560 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:40.561  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:42.524  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:42.526 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:42.528  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:43.941  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:43.942 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:43.944  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:45.771  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:45.772 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:45.775  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:47.260  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:47.265 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:47.268  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:49.125  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:49.132 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:49.134  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:50.812  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:50.817 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:50.819  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:52.668  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:52.671 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:52.673  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:53.876  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:53.878 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:53.880  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:55.239  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:55.241 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:55.242  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:56.403  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:56.409 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:56.413  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:58.288  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:58.288 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:58.288  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:07:59.451  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:07:59.452 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:07:59.452  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:00.807  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:00.808 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:00.814  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:02.557  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:02.558 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:02.559  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:04.338  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:04.338 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:04.339  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:05.659  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:05.659 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:05.660  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:07.702  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:07.703 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:07.703  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:09.625  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:09.625 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:09.626  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:11.590  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:11.591 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:11.591  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:27.276  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:27.281 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:27.283  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:28.950  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:28.951 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:28.953  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:30.247  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:30.248 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:30.248  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:32.190  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:32.197 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:32.197  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:33.345  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:33.351 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:33.352  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:35.066  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:35.069 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:35.071  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:36.480  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:36.485 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:36.487  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:38.533  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:38.535 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:38.537  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:40.099  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:40.102 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:40.104  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:41.810  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:41.813 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:41.815  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:43.562  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:43.564 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:43.566  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:45.412  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:45.412 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:45.413  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:47.265  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:47.265 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:47.266  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:48.928  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:48.929 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:48.929  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:50.526  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:50.527 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:50.529  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:52.595  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:52.596 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:52.670  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:54.143  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:54.144 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:54.144  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:55.808  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:55.809 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:55.810  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:57.592  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:57.593 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:57.593  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:08:59.533  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:08:59.534 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:08:59.535  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:09:00.841  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:09:00.842 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:09:00.843  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:09:02.743  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:09:02.743 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:09:02.744  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:09:03.995  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:09:03.995 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:09:03.996  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:00.316  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:00.446 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:00.470  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:02.538  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:02.538 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:02.539  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:03.942  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:03.943 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:03.944  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:05.171  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:05.171 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:05.172  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:06.616  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:06.617 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:06.617  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:07.987  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:07.989 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:07.990  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:09.617  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:09.626 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:09.628  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:11.152  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:11.155 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:11.162  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:17:13.084  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:17:13.094 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:17:13.095  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:18.359  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:18.364 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:18.366  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:20.400  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:20.401 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:20.401  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:21.568  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:21.568 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:21.569  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:23.513  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:23.514 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:23.514  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:25.369  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:25.370 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:25.370  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:26.889  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:26.889 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:26.890  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:27:28.870  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:27:28.870 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:27:28.870  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:08.315  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:08.450 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:08.461  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:09.969  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:09.970 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:09.971  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:12.069  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:12.070 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:12.071  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:14.108  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:14.109 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:14.109  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:15.406  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:15.407 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:15.409  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:16.623  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:16.626 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:16.627  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:18.230  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:18.232 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:18.234  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:20.120  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:20.122 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:20.124  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:21.622  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:21.628 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:21.630  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:22.933  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:22.936 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:22.937  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:24.347  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:24.349 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:24.351  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:25.888  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:25.891 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:25.899  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:27.561  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:27.562 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:27.563  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:39:28.859  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:39:28.859 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:39:28.860  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:47.046  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:47.051 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:47.054  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:48.260  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:48.261 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:48.261  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:49.792  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:49.798 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:49.798  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:51.480  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:51.481 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:51.481  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:53.346  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:53.349 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:53.351  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:54.762  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:54.771 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:41:54.773  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0315 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:41:56.542  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:56.570  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-04-01 08:41:56.670  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b0315 has expired
2019-04-01 08:41:56.676  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b0315 has expired, closing socket connection
2019-04-01 08:41:56.672  INFO 43296 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Expired)
2019-04-01 08:41:56.740  INFO 43296 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.170.0.42:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@19c6cc8f
2019-04-01 08:41:56.803  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:41:56.801  INFO 43296 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b0315
2019-04-01 08:41:56.811  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-04-01 08:41:56.824  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b0317, negotiated timeout = 30000
2019-04-01 08:41:56.830  INFO 43296 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
2019-04-01 08:42:50.125  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 49770ms for sessionid 0x100fc439b1b0317
2019-04-01 08:42:50.132  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 49770ms for sessionid 0x100fc439b1b0317, closing socket connection and attempting reconnect
2019-04-01 08:42:50.248  INFO 43296 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Disconnected)
2019-04-01 08:42:51.747  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:42:51.749 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:42:51.751  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0317 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:42:53.056  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:42:53.062 ERROR 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-04-01 08:42:53.062  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b0317 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-04-01 08:42:54.791  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:42:55.208  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-04-01 08:42:55.714  INFO 43296 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Expired)
2019-04-01 08:42:55.718  WARN 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b0317 has expired
2019-04-01 08:42:55.726  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b0317 has expired, closing socket connection
2019-04-01 08:42:55.722  INFO 43296 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.170.0.42:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@19c6cc8f
2019-04-01 08:42:55.749  INFO 43296 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b0317
2019-04-01 08:42:55.783  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-01 08:42:55.798  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-04-01 08:42:55.806  INFO 43296 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b031a, negotiated timeout = 30000
2019-04-01 08:42:55.809  INFO 43296 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
2019-04-01 11:28:27.036  INFO 43296 --- [Thread-24] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@5674e1f2: startup date [Thu Mar 21 21:28:36 CST 2019]; root of context hierarchy
2019-04-01 11:28:27.038  INFO 43296 --- [ZkClient-EventThread-54-192.170.0.42:2181] org.I0Itec.zkclient.ZkEventThread        : Terminate ZkClient event thread.
2019-04-01 11:28:27.047  INFO 43296 --- [DubboShutdownHook] org.apache.zookeeper.ZooKeeper           : Session: 0x100fc439b1b031a closed
2019-04-01 11:28:27.050  INFO 43296 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b031a
2019-04-01 11:28:27.068  INFO 43296 --- [Thread-24] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2019-04-01 11:28:27.071  INFO 43296 --- [Thread-24] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2019-04-01 11:28:27.080  INFO 43296 --- [Thread-24] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
