2019-03-28 08:28:35.558  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 31565057ms for sessionid 0x100fc439b1b02cc
2019-03-28 08:28:35.669  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 31565057ms for sessionid 0x100fc439b1b02cc, closing socket connection and attempting reconnect
2019-03-28 08:28:37.531  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:28:37.534 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:28:37.550  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:28:39.403  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:28:39.408 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:28:39.409  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:28:41.032  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:28:41.034 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:28:41.036  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:23.445  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:23.454 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:23.457  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:24.830  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:24.830 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:24.830  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:26.490  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:26.491 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:26.491  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:27.807  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:27.807 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:27.807  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:29.423  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:29.434 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:29.434  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:31.503  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:31.504 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-28 08:47:31.505  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b02cc for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-28 08:47:33.321  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:33.327  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-28 08:47:33.344  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b02cc has expired
2019-03-28 08:47:33.344  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Expired)
2019-03-28 08:47:33.345  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b02cc has expired, closing socket connection
2019-03-28 08:47:33.346  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.170.0.42:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@3db414ee
2019-03-28 08:47:33.348  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-28 08:47:33.348  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b02cc
2019-03-28 08:47:33.349  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-28 08:47:33.353  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b02cd, negotiated timeout = 30000
2019-03-28 08:47:33.354  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
